name: Deploy SEP Web Customer to GCP

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }} # Lấy dữ liệu từ GitHub
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          envs: ENV_FILE # Khai báo biến môi trường cho script
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            cd /var/www/sep-web-customer
            
            # 1. Tự động tạo file .env từ biến GitHub Secret
            echo "$ENV_FILE" > .env
            
            # 2. Pull code mới
            git reset --hard
            git pull origin main
            
            # 3. Cài đặt và chạy lại
            npm install
            pm2 restart sep-web-dev || pm2 start npm --name "sep-web-dev" -- run dev
