name: Deploy SEP Web Customer to GCP

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          envs: ENV_FILE
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            cd /var/www/sep-web-customer
            
            # 1. Tự động tạo file .env từ biến GitHub Secret
            echo "$ENV_FILE" > .env
            
            # 2. Pull code mới
            git reset --hard
            git pull origin main
            
            # 3. Cài đặt thư viện
            npm install
            
            # 4. Build dự án Next.js cho môi trường Production (BƯỚC MỚI)
            npm run build
            
            # 5. Khởi động lại ứng dụng ở chế độ production
            pm2 restart sep-web-prod || pm2 start npm --name "sep-web-prod" -- start
